# 数据库
DATABASE:
  host: 103.227.122.146
  port: 6302
  user: hq_db
  password: QDa,.@tl5Q.F
  database: hq_study_test


# 邮件信息
MAIL:
  sender: xxxxx@xxx.com
  receivers: xxxxx@xxx.com
  mail_host: smtphm.qiye.163.com
  mail_pass: xxxxxxx
  subject: 【web端ui自动化测试报告】
  content:  UI自动化测试已完成，报告详情内容请查看附件    UI测试范围：  xxxxxxxxxxx


